const HISTORY_KEY="anicreator_history_v2";const MAX_HISTORY=100;
export function savedHistory(){try{const v=localStorage.getItem(HISTORY_KEY);if(!v)return[];const d=JSON.parse(v);return Array.isArray(d)?d:[]}catch(e){console.error("History error:",e);return[]}}
export function getSavedHistory(){return savedHistory()}
function save(l){localStorage.setItem(HISTORY_KEY,JSON.stringify(l))}
function createId(d){if(!d)return"";const a=String(d.anime_slug||d.anime_id||"").trim(),s=String(d.season_number||1).trim(),e=String(d.episode_number||1).trim();return a?a+"|s"+s+"|e"+e:""}
export function addHistory(d){if(!d)return false;const id=createId(d);if(!id){console.warn("History: missing anime slug",d);return false}let l=savedHistory().filter(x=>x.id!==id);const type=String(d.type||"anime").toLowerCase()==="movie"?"movie":"anime";l.unshift({id,anime_slug:String(d.anime_slug||d.anime_id||""),anime_title:String(d.anime_title||""),anime_image:String(d.anime_image||d.poster||""),season_number:Number(d.season_number||1),episode_number:Number(d.episode_number||1),title:String(d.title||d.episode_title||""),episode_title:String(d.episode_title||d.title||""),thumbnail:String(d.thumbnail||d.episode_thumb||d.anime_image||d.poster||""),episode_thumb:String(d.episode_thumb||d.thumbnail||d.anime_image||d.poster||""),type,watched_at:Date.now()});save(l.slice(0,MAX_HISTORY));window.dispatchEvent(new Event("historyUpdated"));return true}
export function removeHistory(id){save(savedHistory().filter(x=>x.id!==id));window.dispatchEvent(new Event("historyUpdated"));return true}
export function clearHistory(){localStorage.removeItem(HISTORY_KEY);window.dispatchEvent(new Event("historyUpdated"))}
export function hasHistory(d){const id=createId(d);return savedHistory().some(x=>x.id===id)}
export function getLastWatched(slug){return savedHistory().find(x=>x.anime_slug===slug)||null}
export function subscribeHistory(cb){if(typeof cb!=="function")return()=>{};cb(savedHistory());function u(){cb(savedHistory())}function s(e){if(e.key===HISTORY_KEY)u()}window.addEventListener("historyUpdated",u);window.addEventListener("storage",s);return()=>{window.removeEventListener("historyUpdated",u);window.removeEventListener("storage",s)}}
